name: Build

on: push

jobs:
  push:
    name: onPush
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Build
        run: ./gradlew clean assemble
      - name: Tests
        run: ./gradlew clean test